a14x: Misc changes

diff --git a/recovery/root/system/bin/multidisabler b/recovery/root/system/bin/multidisabler
--- a/recovery/root/system/bin/multidisabler
+++ b/recovery/root/system/bin/multidisabler
@@ -4,43 +4,25 @@
 #
 # Use this to prime your device after installing TWRP.
 
-ram=/ramfs
-vendor_image=${ram}/vendor.img
+vendor=/tmp/vendor.img
 
-md5() {
-  md5sum -b "$1" | cut -d' ' -f1
-}
-
-disable_encryption() {
-    echo "- Disabling encryption..."
-    chksum=$(md5 "$vendor_image")
-    # Target: /vendor/etc/fstab.*
-    gnused -i -b 's|fileencryption=|notencryptable=|g' $vendor_image
-    nchksum=$(md5 "$vendor_image")
-    if [ "$chksum" != "$nchksum" ]; then
-        echo " -    Success..."
-    else
+patch_file() {
+    echo " - Disabling encryption and recovery restoration..."
+    bxhsed --quiet $1 '/vendor/recovery-from-boot.p|/vendor/recovery-from-bsod.p' 'fileencryption=|notencryptable='
+    ret=$?
+    if [ "$ret" -gt "0" ]; then
+        echo " -    Success... (${ret})"
+    elif [ "$ret" -eq "0" ]; then
         echo " -    Already disabled..."
-    fi
-}
-
-disable_recovery_restoration() {
-    echo "- Disabling recovery restoration..."
-    chksum=$(md5 "$vendor_image")
-    # Target: /vendor/bin/install-recovery.sh (is the script that does the restoration, so we edit it.)
-    gnused -i -b 's|/vendor/recovery-from-boot.p|/vendor/recovery-from-bsod.p|g' $vendor_image
-    nchksum=$(md5 "$vendor_image")
-    if [ "$chksum" != "$nchksum" ]; then
-        echo " -    Success..."
     else
-        echo " -    Already disabled..."
+        echo " -    Failed! (exit code: ${ret})"
     fi
 }
 
 fsck() {
-    fsck.erofs $vendor_image
+    fsck.erofs $1
     if [ "$?" != "0" ]; then
-        echo " - ERROR: Failed to run fsck!!! (Unexpected behavior)"
+        echo " - Error: Failed to run fsck!"
     fi
 }
 
@@ -93,7 +75,7 @@ fi
 
 dm_block=$(df -t erofs | grep "/vendor" | cut -DF1)
 if [ "$dm_block" == "" ]; then
-    echo " - ERROR: Could not determine vendor block..."
+    echo " - Error: Could not determine vendor block..."
     exit 1
 fi
 echo " - Detected vendor at ${dm_block}"
@@ -104,36 +86,14 @@ if mount | grep -q /vendor; then
   exit 1
 fi
 
-# /tmp has only half ram, so we mount another tmpfs
-if mount | grep -q ${ram}; then
-    umount ${ram} &>/dev/null
-fi
-mkdir -p ${ram}
-mount -t tmpfs -o size=$(free -b | awk 'NR==2{print $2}') none ${ram}
-if ! mount | grep -q ${ram}; then
-    echo " - Couldn't mount RAMFS for storing vendor..."
-    exit 1
-fi
+dd if=$dm_block of=$vendor bs=2097152 status=none
+patch_file $vendor
+fsck $vendor
+lptools unmap vendor
+lpadd --replace --readonly /dev/block/by-name/super vendor group_basic $vendor
+lptools map vendor
 
-echo " - Copying vendor to RAM..."
-dd if=$dm_block of=$vendor_image bs=2097152
-if [ "$?" != "0" ]; then
-    echo "-    Failed..."
-    exit 1
-fi
-echo "-    Done..."
-
-shrink "$vendor_image"
-
-disable_encryption
-disable_recovery_restoration
-fsck
-
-echo " - Flashing vendor..."
-dd if=$vendor_image of=$dm_block bs=2097152
-echo " - Cleaning..."
-rm -f $vendor_image
-umount ${ram} &>/dev/null
+rm -f $vendor
 
 echo " "
 echo " - Finished."
